// Auto-generated by generation/make_srams.py -- do not edit by hand.
// lambdalib-backed wrappers for the SonicBOOM (MegaBoomV3Config) SRAM
// blackboxes plus a synthesis stub for plusarg_reader.

// ---- single-port (1RW) SRAMs -> la_spram ----

module cc_dir_ext(
   input  [9:0]  RW0_addr,
   input         RW0_clk,
   input  [135:0] RW0_wdata,
   output [135:0] RW0_rdata,
   input         RW0_en,
   input         RW0_wmode,
   input  [7:0]  RW0_wmask
   );

   localparam DW = 136;
   localparam AW = 10;
   wire [DW-1:0] bitmask;
   genvar gi;
   generate
      for (gi = 0; gi < DW; gi = gi + 1) begin: gmask
         assign bitmask[gi] = RW0_wmask[gi / 17];
      end
   endgenerate

   la_spram #(.DW(DW), .AW(AW), .BYTEMASK(0)) mem (
      .clk     (RW0_clk),
      .ce      (RW0_en),
      .we      (RW0_en & RW0_wmode),
      .wmask   (bitmask),
      .addr    (RW0_addr),
      .din     (RW0_wdata),
      .dout    (RW0_rdata),
      .selctrl (1'b0),
      .ctrl    (32'b0),
      .status  ());

endmodule


module cc_banks_0_ext(
   input  [12:0]  RW0_addr,
   input         RW0_clk,
   input  [63:0] RW0_wdata,
   output [63:0] RW0_rdata,
   input         RW0_en,
   input         RW0_wmode
   );

   localparam DW = 64;
   localparam AW = 13;
   wire [DW-1:0] bitmask = {DW{1'b1}};

   la_spram #(.DW(DW), .AW(AW), .BYTEMASK(0)) mem (
      .clk     (RW0_clk),
      .ce      (RW0_en),
      .we      (RW0_en & RW0_wmode),
      .wmask   (bitmask),
      .addr    (RW0_addr),
      .din     (RW0_wdata),
      .dout    (RW0_rdata),
      .selctrl (1'b0),
      .ctrl    (32'b0),
      .status  ());

endmodule


module tag_array_ext(
   input  [5:0]  RW0_addr,
   input         RW0_clk,
   input  [175:0] RW0_wdata,
   output [175:0] RW0_rdata,
   input         RW0_en,
   input         RW0_wmode,
   input  [7:0]  RW0_wmask
   );

   localparam DW = 176;
   localparam AW = 6;
   wire [DW-1:0] bitmask;
   genvar gi;
   generate
      for (gi = 0; gi < DW; gi = gi + 1) begin: gmask
         assign bitmask[gi] = RW0_wmask[gi / 22];
      end
   endgenerate

   la_spram #(.DW(DW), .AW(AW), .BYTEMASK(0)) mem (
      .clk     (RW0_clk),
      .ce      (RW0_en),
      .we      (RW0_en & RW0_wmode),
      .wmask   (bitmask),
      .addr    (RW0_addr),
      .din     (RW0_wdata),
      .dout    (RW0_rdata),
      .selctrl (1'b0),
      .ctrl    (32'b0),
      .status  ());

endmodule


module tag_array_0_ext(
   input  [5:0]  RW0_addr,
   input         RW0_clk,
   input  [159:0] RW0_wdata,
   output [159:0] RW0_rdata,
   input         RW0_en,
   input         RW0_wmode,
   input  [7:0]  RW0_wmask
   );

   localparam DW = 160;
   localparam AW = 6;
   wire [DW-1:0] bitmask;
   genvar gi;
   generate
      for (gi = 0; gi < DW; gi = gi + 1) begin: gmask
         assign bitmask[gi] = RW0_wmask[gi / 20];
      end
   endgenerate

   la_spram #(.DW(DW), .AW(AW), .BYTEMASK(0)) mem (
      .clk     (RW0_clk),
      .ce      (RW0_en),
      .we      (RW0_en & RW0_wmode),
      .wmask   (bitmask),
      .addr    (RW0_addr),
      .din     (RW0_wdata),
      .dout    (RW0_rdata),
      .selctrl (1'b0),
      .ctrl    (32'b0),
      .status  ());

endmodule


module dataArrayB0Way_0_ext(
   input  [7:0]  RW0_addr,
   input         RW0_clk,
   input  [63:0] RW0_wdata,
   output [63:0] RW0_rdata,
   input         RW0_en,
   input         RW0_wmode
   );

   localparam DW = 64;
   localparam AW = 8;
   wire [DW-1:0] bitmask = {DW{1'b1}};

   la_spram #(.DW(DW), .AW(AW), .BYTEMASK(0)) mem (
      .clk     (RW0_clk),
      .ce      (RW0_en),
      .we      (RW0_en & RW0_wmode),
      .wmask   (bitmask),
      .addr    (RW0_addr),
      .din     (RW0_wdata),
      .dout    (RW0_rdata),
      .selctrl (1'b0),
      .ctrl    (32'b0),
      .status  ());

endmodule


module l2_tlb_ram_0_ext(
   input  [8:0]  RW0_addr,
   input         RW0_clk,
   input  [44:0] RW0_wdata,
   output [44:0] RW0_rdata,
   input         RW0_en,
   input         RW0_wmode
   );

   localparam DW = 45;
   localparam AW = 9;
   wire [DW-1:0] bitmask = {DW{1'b1}};

   la_spram #(.DW(DW), .AW(AW), .BYTEMASK(0)) mem (
      .clk     (RW0_clk),
      .ce      (RW0_en),
      .we      (RW0_en & RW0_wmode),
      .wmask   (bitmask),
      .addr    (RW0_addr),
      .din     (RW0_wdata),
      .dout    (RW0_rdata),
      .selctrl (1'b0),
      .ctrl    (32'b0),
      .status  ());

endmodule


module mem_ext(
   input  [12:0]  RW0_addr,
   input         RW0_clk,
   input  [63:0] RW0_wdata,
   output [63:0] RW0_rdata,
   input         RW0_en,
   input         RW0_wmode,
   input  [7:0]  RW0_wmask
   );

   localparam DW = 64;
   localparam AW = 13;
   wire [DW-1:0] bitmask;
   genvar gi;
   generate
      for (gi = 0; gi < DW; gi = gi + 1) begin: gmask
         assign bitmask[gi] = RW0_wmask[gi / 8];
      end
   endgenerate

   la_spram #(.DW(DW), .AW(AW), .BYTEMASK(0)) mem (
      .clk     (RW0_clk),
      .ce      (RW0_en),
      .we      (RW0_en & RW0_wmode),
      .wmask   (bitmask),
      .addr    (RW0_addr),
      .din     (RW0_wdata),
      .dout    (RW0_rdata),
      .selctrl (1'b0),
      .ctrl    (32'b0),
      .status  ());

endmodule

// ---- one-read one-write (1R1W) SRAMs -> la_dpram ----

module array_0_0_ext(
   input  [7:0]  R0_addr,
   input         R0_clk,
   output [127:0] R0_data,
   input         R0_en,
   input  [7:0]  W0_addr,
   input         W0_clk,
   input  [127:0] W0_data,
   input         W0_en,
   input  [1:0]  W0_mask
   );

   localparam DW = 128;
   localparam AW = 8;
   wire [DW-1:0] bitmask;
   genvar gi;
   generate
      for (gi = 0; gi < DW; gi = gi + 1) begin: gmask
         assign bitmask[gi] = W0_mask[gi / 64];
      end
   endgenerate

   la_dpram #(.DW(DW), .AW(AW), .BYTEMASK(0)) mem (
      .wr_clk  (W0_clk),
      .wr_ce   (W0_en),
      .wr_we   (W0_en),
      .wr_wmask(bitmask),
      .wr_addr (W0_addr),
      .wr_din  (W0_data),
      .rd_clk  (R0_clk),
      .rd_ce   (R0_en),
      .rd_addr (R0_addr),
      .rd_dout (R0_data),
      .selctrl (1'b0),
      .ctrl    (32'b0),
      .status  ());

endmodule


module hi_us_ext(
   input  [6:0]  R0_addr,
   input         R0_clk,
   output [3:0] R0_data,
   input         R0_en,
   input  [6:0]  W0_addr,
   input         W0_clk,
   input  [3:0] W0_data,
   input         W0_en,
   input  [3:0]  W0_mask
   );

   localparam DW = 4;
   localparam AW = 7;
   wire [DW-1:0] bitmask;
   genvar gi;
   generate
      for (gi = 0; gi < DW; gi = gi + 1) begin: gmask
         assign bitmask[gi] = W0_mask[gi / 1];
      end
   endgenerate

   la_dpram #(.DW(DW), .AW(AW), .BYTEMASK(0)) mem (
      .wr_clk  (W0_clk),
      .wr_ce   (W0_en),
      .wr_we   (W0_en),
      .wr_wmask(bitmask),
      .wr_addr (W0_addr),
      .wr_din  (W0_data),
      .rd_clk  (R0_clk),
      .rd_ce   (R0_en),
      .rd_addr (R0_addr),
      .rd_dout (R0_data),
      .selctrl (1'b0),
      .ctrl    (32'b0),
      .status  ());

endmodule


module hi_us_0_ext(
   input  [7:0]  R0_addr,
   input         R0_clk,
   output [3:0] R0_data,
   input         R0_en,
   input  [7:0]  W0_addr,
   input         W0_clk,
   input  [3:0] W0_data,
   input         W0_en,
   input  [3:0]  W0_mask
   );

   localparam DW = 4;
   localparam AW = 8;
   wire [DW-1:0] bitmask;
   genvar gi;
   generate
      for (gi = 0; gi < DW; gi = gi + 1) begin: gmask
         assign bitmask[gi] = W0_mask[gi / 1];
      end
   endgenerate

   la_dpram #(.DW(DW), .AW(AW), .BYTEMASK(0)) mem (
      .wr_clk  (W0_clk),
      .wr_ce   (W0_en),
      .wr_we   (W0_en),
      .wr_wmask(bitmask),
      .wr_addr (W0_addr),
      .wr_din  (W0_data),
      .rd_clk  (R0_clk),
      .rd_ce   (R0_en),
      .rd_addr (R0_addr),
      .rd_dout (R0_data),
      .selctrl (1'b0),
      .ctrl    (32'b0),
      .status  ());

endmodule


module table_ext(
   input  [6:0]  R0_addr,
   input         R0_clk,
   output [43:0] R0_data,
   input         R0_en,
   input  [6:0]  W0_addr,
   input         W0_clk,
   input  [43:0] W0_data,
   input         W0_en,
   input  [3:0]  W0_mask
   );

   localparam DW = 44;
   localparam AW = 7;
   wire [DW-1:0] bitmask;
   genvar gi;
   generate
      for (gi = 0; gi < DW; gi = gi + 1) begin: gmask
         assign bitmask[gi] = W0_mask[gi / 11];
      end
   endgenerate

   la_dpram #(.DW(DW), .AW(AW), .BYTEMASK(0)) mem (
      .wr_clk  (W0_clk),
      .wr_ce   (W0_en),
      .wr_we   (W0_en),
      .wr_wmask(bitmask),
      .wr_addr (W0_addr),
      .wr_din  (W0_data),
      .rd_clk  (R0_clk),
      .rd_ce   (R0_en),
      .rd_addr (R0_addr),
      .rd_dout (R0_data),
      .selctrl (1'b0),
      .ctrl    (32'b0),
      .status  ());

endmodule


module table_0_ext(
   input  [7:0]  R0_addr,
   input         R0_clk,
   output [47:0] R0_data,
   input         R0_en,
   input  [7:0]  W0_addr,
   input         W0_clk,
   input  [47:0] W0_data,
   input         W0_en,
   input  [3:0]  W0_mask
   );

   localparam DW = 48;
   localparam AW = 8;
   wire [DW-1:0] bitmask;
   genvar gi;
   generate
      for (gi = 0; gi < DW; gi = gi + 1) begin: gmask
         assign bitmask[gi] = W0_mask[gi / 12];
      end
   endgenerate

   la_dpram #(.DW(DW), .AW(AW), .BYTEMASK(0)) mem (
      .wr_clk  (W0_clk),
      .wr_ce   (W0_en),
      .wr_we   (W0_en),
      .wr_wmask(bitmask),
      .wr_addr (W0_addr),
      .wr_din  (W0_data),
      .rd_clk  (R0_clk),
      .rd_ce   (R0_en),
      .rd_addr (R0_addr),
      .rd_dout (R0_data),
      .selctrl (1'b0),
      .ctrl    (32'b0),
      .status  ());

endmodule


module table_1_ext(
   input  [6:0]  R0_addr,
   input         R0_clk,
   output [51:0] R0_data,
   input         R0_en,
   input  [6:0]  W0_addr,
   input         W0_clk,
   input  [51:0] W0_data,
   input         W0_en,
   input  [3:0]  W0_mask
   );

   localparam DW = 52;
   localparam AW = 7;
   wire [DW-1:0] bitmask;
   genvar gi;
   generate
      for (gi = 0; gi < DW; gi = gi + 1) begin: gmask
         assign bitmask[gi] = W0_mask[gi / 13];
      end
   endgenerate

   la_dpram #(.DW(DW), .AW(AW), .BYTEMASK(0)) mem (
      .wr_clk  (W0_clk),
      .wr_ce   (W0_en),
      .wr_we   (W0_en),
      .wr_wmask(bitmask),
      .wr_addr (W0_addr),
      .wr_din  (W0_data),
      .rd_clk  (R0_clk),
      .rd_ce   (R0_en),
      .rd_addr (R0_addr),
      .rd_dout (R0_data),
      .selctrl (1'b0),
      .ctrl    (32'b0),
      .status  ());

endmodule


module meta_0_ext(
   input  [6:0]  R0_addr,
   input         R0_clk,
   output [119:0] R0_data,
   input         R0_en,
   input  [6:0]  W0_addr,
   input         W0_clk,
   input  [119:0] W0_data,
   input         W0_en,
   input  [3:0]  W0_mask
   );

   localparam DW = 120;
   localparam AW = 7;
   wire [DW-1:0] bitmask;
   genvar gi;
   generate
      for (gi = 0; gi < DW; gi = gi + 1) begin: gmask
         assign bitmask[gi] = W0_mask[gi / 30];
      end
   endgenerate

   la_dpram #(.DW(DW), .AW(AW), .BYTEMASK(0)) mem (
      .wr_clk  (W0_clk),
      .wr_ce   (W0_en),
      .wr_we   (W0_en),
      .wr_wmask(bitmask),
      .wr_addr (W0_addr),
      .wr_din  (W0_data),
      .rd_clk  (R0_clk),
      .rd_ce   (R0_en),
      .rd_addr (R0_addr),
      .rd_dout (R0_data),
      .selctrl (1'b0),
      .ctrl    (32'b0),
      .status  ());

endmodule


module meta_ext(
   input  [5:0]  R0_addr,
   input         R0_clk,
   output [239:0] R0_data,
   input         R0_en,
   input  [5:0]  W0_addr,
   input         W0_clk,
   input  [239:0] W0_data,
   input         W0_en
   );

   localparam DW = 240;
   localparam AW = 6;
   wire [DW-1:0] bitmask = {DW{1'b1}};

   la_dpram #(.DW(DW), .AW(AW), .BYTEMASK(0)) mem (
      .wr_clk  (W0_clk),
      .wr_ce   (W0_en),
      .wr_we   (W0_en),
      .wr_wmask(bitmask),
      .wr_addr (W0_addr),
      .wr_din  (W0_data),
      .rd_clk  (R0_clk),
      .rd_ce   (R0_en),
      .rd_addr (R0_addr),
      .rd_dout (R0_data),
      .selctrl (1'b0),
      .ctrl    (32'b0),
      .status  ());

endmodule


module btb_0_ext(
   input  [6:0]  R0_addr,
   input         R0_clk,
   output [55:0] R0_data,
   input         R0_en,
   input  [6:0]  W0_addr,
   input         W0_clk,
   input  [55:0] W0_data,
   input         W0_en,
   input  [3:0]  W0_mask
   );

   localparam DW = 56;
   localparam AW = 7;
   wire [DW-1:0] bitmask;
   genvar gi;
   generate
      for (gi = 0; gi < DW; gi = gi + 1) begin: gmask
         assign bitmask[gi] = W0_mask[gi / 14];
      end
   endgenerate

   la_dpram #(.DW(DW), .AW(AW), .BYTEMASK(0)) mem (
      .wr_clk  (W0_clk),
      .wr_ce   (W0_en),
      .wr_we   (W0_en),
      .wr_wmask(bitmask),
      .wr_addr (W0_addr),
      .wr_din  (W0_data),
      .rd_clk  (R0_clk),
      .rd_ce   (R0_en),
      .rd_addr (R0_addr),
      .rd_dout (R0_data),
      .selctrl (1'b0),
      .ctrl    (32'b0),
      .status  ());

endmodule


module ebtb_ext(
   input  [6:0]  R0_addr,
   input         R0_clk,
   output [39:0] R0_data,
   input         R0_en,
   input  [6:0]  W0_addr,
   input         W0_clk,
   input  [39:0] W0_data,
   input         W0_en
   );

   localparam DW = 40;
   localparam AW = 7;
   wire [DW-1:0] bitmask = {DW{1'b1}};

   la_dpram #(.DW(DW), .AW(AW), .BYTEMASK(0)) mem (
      .wr_clk  (W0_clk),
      .wr_ce   (W0_en),
      .wr_we   (W0_en),
      .wr_wmask(bitmask),
      .wr_addr (W0_addr),
      .wr_din  (W0_data),
      .rd_clk  (R0_clk),
      .rd_ce   (R0_en),
      .rd_addr (R0_addr),
      .rd_dout (R0_data),
      .selctrl (1'b0),
      .ctrl    (32'b0),
      .status  ());

endmodule


module data_ext(
   input  [10:0]  R0_addr,
   input         R0_clk,
   output [7:0] R0_data,
   input         R0_en,
   input  [10:0]  W0_addr,
   input         W0_clk,
   input  [7:0] W0_data,
   input         W0_en,
   input  [3:0]  W0_mask
   );

   localparam DW = 8;
   localparam AW = 11;
   wire [DW-1:0] bitmask;
   genvar gi;
   generate
      for (gi = 0; gi < DW; gi = gi + 1) begin: gmask
         assign bitmask[gi] = W0_mask[gi / 2];
      end
   endgenerate

   la_dpram #(.DW(DW), .AW(AW), .BYTEMASK(0)) mem (
      .wr_clk  (W0_clk),
      .wr_ce   (W0_en),
      .wr_we   (W0_en),
      .wr_wmask(bitmask),
      .wr_addr (W0_addr),
      .wr_din  (W0_data),
      .rd_clk  (R0_clk),
      .rd_ce   (R0_en),
      .rd_addr (R0_addr),
      .rd_dout (R0_data),
      .selctrl (1'b0),
      .ctrl    (32'b0),
      .status  ());

endmodule


module ghist_0_ext(
   input  [5:0]  R0_addr,
   input         R0_clk,
   output [71:0] R0_data,
   input         R0_en,
   input  [5:0]  W0_addr,
   input         W0_clk,
   input  [71:0] W0_data,
   input         W0_en
   );

   localparam DW = 72;
   localparam AW = 6;
   wire [DW-1:0] bitmask = {DW{1'b1}};

   la_dpram #(.DW(DW), .AW(AW), .BYTEMASK(0)) mem (
      .wr_clk  (W0_clk),
      .wr_ce   (W0_en),
      .wr_we   (W0_en),
      .wr_wmask(bitmask),
      .wr_addr (W0_addr),
      .wr_din  (W0_data),
      .rd_clk  (R0_clk),
      .rd_ce   (R0_en),
      .rd_addr (R0_addr),
      .rd_dout (R0_data),
      .selctrl (1'b0),
      .ctrl    (32'b0),
      .status  ());

endmodule


module rob_debug_inst_mem_ext(
   input  [4:0]  R0_addr,
   input         R0_clk,
   output [127:0] R0_data,
   input         R0_en,
   input  [4:0]  W0_addr,
   input         W0_clk,
   input  [127:0] W0_data,
   input         W0_en,
   input  [3:0]  W0_mask
   );

   localparam DW = 128;
   localparam AW = 5;
   wire [DW-1:0] bitmask;
   genvar gi;
   generate
      for (gi = 0; gi < DW; gi = gi + 1) begin: gmask
         assign bitmask[gi] = W0_mask[gi / 32];
      end
   endgenerate

   la_dpram #(.DW(DW), .AW(AW), .BYTEMASK(0)) mem (
      .wr_clk  (W0_clk),
      .wr_ce   (W0_en),
      .wr_we   (W0_en),
      .wr_wmask(bitmask),
      .wr_addr (W0_addr),
      .wr_din  (W0_data),
      .rd_clk  (R0_clk),
      .rd_ce   (R0_en),
      .rd_addr (R0_addr),
      .rd_dout (R0_data),
      .selctrl (1'b0),
      .ctrl    (32'b0),
      .status  ());

endmodule

// ---- simulation-only plusarg reader (synthesis stub) ----

module plusarg_reader #(
   parameter FORMAT = "borked=%d",
   parameter WIDTH = 1,
   parameter [WIDTH-1:0] DEFAULT = 0
) (
   output [WIDTH-1:0] out
);
   // Synthesis stub: the plusarg is a simulation-only construct; under
   // synthesis the reader simply drives its default (matches Chipyard's
   // `ifdef SYNTHESIS behaviour).
   assign out = DEFAULT;
endmodule

